/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct UpdateRequest {
    #[cfg_attr(feature = "cli", command(flatten))]
    pub data: crate::models::UpdateSdk,
}
