/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct ListRequest {
    #[cfg_attr(feature = "cli", arg(id = "api", long = "api"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api: Option<String>,
    #[cfg_attr(feature = "cli", arg(id = "successful", long = "successful"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub successful: Option<bool>,
}
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GenerateRequest {
    #[cfg_attr(feature = "cli", command(flatten))]
    pub data: crate::models::NewSdk,
}
