/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(untagged)]
pub enum ApiVersion {
    StrEnum(crate::models::VersionTypeEnum),
    Str(String),
}
impl Default for ApiVersion {
    fn default() -> Self {
        ApiVersion::Str(Default::default())
    }
}
