/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum ApiLinkPolicyEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "latest"))]
    #[serde(rename = "latest")]
    Latest,
    #[cfg_attr(feature = "cli", value(name = "pinned"))]
    #[serde(rename = "pinned")]
    Pinned,
}
impl std::fmt::Display for ApiLinkPolicyEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            ApiLinkPolicyEnum::Latest => "latest",
            ApiLinkPolicyEnum::Pinned => "pinned",
        };
        write!(f, "{}", str_val)
    }
}
