/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct ApiLinkReorder {
    #[cfg_attr(feature = "cli", arg(id = "group-id", long = "group-id"))]
    pub group_id: String,
    #[cfg_attr(feature = "cli", arg(id = "id", long = "id"))]
    pub id: String,
    #[cfg_attr(feature = "cli", arg(id = "order", long = "order"))]
    pub order: i64,
}
