/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct ApiLinkApiVersion {
    #[cfg_attr(feature = "cli", arg(id = "api-id", long = "api-id"))]
    pub api_id: String,
    #[cfg_attr(feature = "cli", arg(id = "semver", long = "semver"))]
    pub semver: String,
}
