/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct ApiLinkApiVersion {
    #[cfg_attr(feature = "cli", arg(id = "api-project-id", long = "api-project-id"))]
    pub api_project_id: String,
    #[cfg_attr(
        feature = "cli",
        arg(id = "api-project-title", long = "api-project-title")
    )]
    pub api_project_title: String,
    #[cfg_attr(feature = "cli", arg(id = "id", long = "id"))]
    pub id: String,
    #[cfg_attr(feature = "cli", arg(id = "semver", long = "semver"))]
    pub semver: String,
}
