/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct ApiSpec {
    #[cfg_attr(feature = "cli", arg(id = "api", long = "api"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_json::<crate::models::Api>)
    )]
    pub api: crate::models::Api,
    #[cfg_attr(feature = "cli", arg(id = "created-at", long = "created-at"))]
    pub created_at: String,
    #[cfg_attr(feature = "cli", arg(id = "id", long = "id"))]
    pub id: String,
    #[cfg_attr(feature = "cli", arg(id = "mock-server", long = "mock-server"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_json::<crate::models::ApiMockServer>)
    )]
    pub mock_server: crate::models::ApiMockServer,
    #[cfg_attr(feature = "cli", arg(id = "notes", long = "notes"))]
    pub notes: String,
    #[cfg_attr(feature = "cli", arg(id = "version", long = "version"))]
    pub version: String,
}
