/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct DocProjectLogos {
    #[cfg_attr(feature = "cli", arg(id = "dark", long = "dark"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_json::<crate::models::Asset>)
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub dark: Option<crate::models::Asset>,
    #[cfg_attr(feature = "cli", arg(id = "favicon", long = "favicon"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_json::<crate::models::Asset>)
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub favicon: Option<crate::models::Asset>,
    #[cfg_attr(feature = "cli", arg(id = "light", long = "light"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_json::<crate::models::Asset>)
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub light: Option<crate::models::Asset>,
}
