/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct DocProject {
    #[cfg_attr(feature = "cli", arg(id = "created-at", long = "created-at"))]
    pub created_at: String,
    #[cfg_attr(
        feature = "cli",
        arg(id = "current-version-id", long = "current-version-id")
    )]
    pub current_version_id: String,
    #[cfg_attr(feature = "cli", arg(id = "domains", long = "domains"))]
    #[cfg_attr(
        feature = "cli",
        arg(
            value_parser = crate::core::clap::parse_json::<crate::models::DocProjectDomains>
        )
    )]
    pub domains: crate::models::DocProjectDomains,
    #[cfg_attr(feature = "cli", arg(id = "id", long = "id"))]
    pub id: String,
    #[cfg_attr(feature = "cli", arg(id = "logos", long = "logos"))]
    #[cfg_attr(
        feature = "cli",
        arg(
            value_parser = crate::core::clap::parse_json::<crate::models::DocProjectLogos>
        )
    )]
    pub logos: crate::models::DocProjectLogos,
    #[cfg_attr(feature = "cli", arg(id = "settings", long = "settings"))]
    #[cfg_attr(
        feature = "cli",
        arg(
            value_parser = crate::core::clap::parse_json::<crate::models::DocProjectSettings>
        )
    )]
    pub settings: crate::models::DocProjectSettings,
    #[cfg_attr(feature = "cli", arg(id = "title", long = "title"))]
    pub title: String,
}
