/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct GuideContent {
    #[cfg_attr(feature = "cli", arg(id = "content", long = "content"))]
    pub content: String,
}
