/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum GuideHrefVariantEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "next"))]
    #[serde(rename = "next")]
    Next,
    #[cfg_attr(feature = "cli", value(name = "prev"))]
    #[serde(rename = "prev")]
    Prev,
}
impl std::fmt::Display for GuideHrefVariantEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            GuideHrefVariantEnum::Next => "next",
            GuideHrefVariantEnum::Prev => "prev",
        };
        write!(f, "{}", str_val)
    }
}
