/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct InitSdkConfig {
    #[cfg_attr(feature = "cli", arg(id = "api-name", long = "api-name"))]
    pub api_name: String,
    #[cfg_attr(feature = "cli", arg(id = "api-version", long = "api-version"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
}
