/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct Invite {
    #[cfg_attr(feature = "cli", arg(id = "email", long = "email"))]
    pub email: String,
    #[cfg_attr(
        feature = "cli",
        arg(id = "role-definition-id", long = "role-definition-id")
    )]
    pub role_definition_id: crate::models::RoleDefinitionIdEnum,
}
