/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct LatestApiLinkPolicy {
    #[cfg_attr(feature = "cli", arg(id = "api-id", long = "api-id"))]
    pub api_id: String,
    #[cfg_attr(feature = "cli", arg(id = "type-field", long = "type-field"))]
    #[serde(rename = "type")]
    pub type_field: crate::models::LatestApiLinkPolicyTypeEnum,
}
