/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct NewDeployment {
    #[cfg_attr(feature = "cli", arg(id = "doc-version-id", long = "doc-version-id"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub doc_version_id: Option<String>,
    #[cfg_attr(feature = "cli", arg(id = "target", long = "target"))]
    pub target: crate::models::DeploymentTargetEnum,
}
