/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct NewApiVersion {
    #[cfg_attr(
        feature = "cli",
        arg(id = "mock-server-enabled", long = "mock-server-enabled")
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mock_server_enabled: Option<bool>,
    #[cfg_attr(feature = "cli", arg(id = "notes", long = "notes"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    #[cfg_attr(feature = "cli", arg(id = "openapi", long = "openapi"))]
    pub openapi: String,
    #[cfg_attr(feature = "cli", arg(id = "semver", long = "semver"))]
    pub semver: String,
}
