/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct NewProjectRole {
    #[cfg_attr(feature = "cli", arg(id = "role", long = "role"))]
    pub role: crate::models::ProjectRoleEnum,
    #[cfg_attr(feature = "cli", arg(id = "user-id", long = "user-id"))]
    pub user_id: String,
}
