/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct NewSdkResponse {
    #[cfg_attr(feature = "cli", arg(id = "patch", long = "patch"))]
    pub patch: String,
}
