/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(untagged)]
pub enum NewApiLinkPolicy {
    LatestApiLinkPolicy(crate::models::LatestApiLinkPolicy),
    PinnedApiLinkPolicy(crate::models::PinnedApiLinkPolicy),
}
impl Default for NewApiLinkPolicy {
    fn default() -> Self {
        NewApiLinkPolicy::PinnedApiLinkPolicy(Default::default())
    }
}
