/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct NewRole {
    #[cfg_attr(feature = "cli", arg(id = "object-id", long = "object-id"))]
    pub object_id: String,
    #[cfg_attr(feature = "cli", arg(id = "object-type", long = "object-type"))]
    pub object_type: crate::models::ObjectTypeEnum,
    #[cfg_attr(
        feature = "cli",
        arg(id = "role-definition-id", long = "role-definition-id")
    )]
    pub role_definition_id: crate::models::RoleDefinitionIdEnum,
    #[cfg_attr(feature = "cli", arg(id = "user-id", long = "user-id"))]
    pub user_id: String,
}
