/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum ObjectTypeEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "api_project"))]
    #[serde(rename = "api_project")]
    ApiProject,
    #[cfg_attr(feature = "cli", value(name = "doc_project"))]
    #[serde(rename = "doc_project")]
    DocProject,
    #[cfg_attr(feature = "cli", value(name = "organization"))]
    #[serde(rename = "organization")]
    Organization,
}
impl std::fmt::Display for ObjectTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            ObjectTypeEnum::ApiProject => "api_project",
            ObjectTypeEnum::DocProject => "doc_project",
            ObjectTypeEnum::Organization => "organization",
        };
        write!(f, "{}", str_val)
    }
}
