/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum OrganizationRoleEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "admin"))]
    #[serde(rename = "admin")]
    Admin,
    #[cfg_attr(feature = "cli", value(name = "manager"))]
    #[serde(rename = "manager")]
    Manager,
    #[cfg_attr(feature = "cli", value(name = "member"))]
    #[serde(rename = "member")]
    Member,
}
impl std::fmt::Display for OrganizationRoleEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            OrganizationRoleEnum::Admin => "admin",
            OrganizationRoleEnum::Manager => "manager",
            OrganizationRoleEnum::Member => "member",
        };
        write!(f, "{}", str_val)
    }
}
