/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct PinnedApiLinkPolicy {
    #[cfg_attr(feature = "cli", arg(id = "api-version-id", long = "api-version-id"))]
    pub api_version_id: String,
    #[cfg_attr(feature = "cli", arg(id = "type-field", long = "type-field"))]
    #[serde(rename = "type")]
    pub type_field: crate::models::PinnedApiLinkPolicyTypeEnum,
}
