/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum ProjectTypeEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "api"))]
    #[serde(rename = "api")]
    Api,
    #[cfg_attr(feature = "cli", value(name = "documentation"))]
    #[serde(rename = "documentation")]
    Documentation,
}
impl std::fmt::Display for ProjectTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            ProjectTypeEnum::Api => "api",
            ProjectTypeEnum::Documentation => "documentation",
        };
        write!(f, "{}", str_val)
    }
}
