/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum ProjectRoleEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "admin"))]
    #[serde(rename = "admin")]
    Admin,
    #[cfg_attr(feature = "cli", value(name = "contributor"))]
    #[serde(rename = "contributor")]
    Contributor,
    #[cfg_attr(feature = "cli", value(name = "viewer"))]
    #[serde(rename = "viewer")]
    Viewer,
}
impl std::fmt::Display for ProjectRoleEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            ProjectRoleEnum::Admin => "admin",
            ProjectRoleEnum::Contributor => "contributor",
            ProjectRoleEnum::Viewer => "viewer",
        };
        write!(f, "{}", str_val)
    }
}
