/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct Role {
    #[cfg_attr(feature = "cli", arg(id = "definition", long = "definition"))]
    #[cfg_attr(
        feature = "cli",
        arg(
            value_parser = crate::core::clap::parse_json::<crate::models::RoleDefinition>
        )
    )]
    pub definition: crate::models::RoleDefinition,
    #[cfg_attr(feature = "cli", arg(id = "id", long = "id"))]
    pub id: String,
    #[cfg_attr(feature = "cli", arg(id = "object-id", long = "object-id"))]
    pub object_id: String,
    #[cfg_attr(feature = "cli", arg(id = "object-type", long = "object-type"))]
    pub object_type: crate::models::ObjectTypeEnum,
    #[cfg_attr(feature = "cli", arg(id = "user", long = "user"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_json::<crate::models::User>)
    )]
    pub user: crate::models::User,
}
