/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum RoleDefinitionIdEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "ApiProjectAdmin"))]
    #[serde(rename = "ApiProjectAdmin")]
    ApiProjectAdmin,
    #[cfg_attr(feature = "cli", value(name = "ApiProjectContributor"))]
    #[serde(rename = "ApiProjectContributor")]
    ApiProjectContributor,
    #[cfg_attr(feature = "cli", value(name = "ApiProjectViewer"))]
    #[serde(rename = "ApiProjectViewer")]
    ApiProjectViewer,
    #[cfg_attr(feature = "cli", value(name = "DocProjectAdmin"))]
    #[serde(rename = "DocProjectAdmin")]
    DocProjectAdmin,
    #[cfg_attr(feature = "cli", value(name = "DocProjectContributor"))]
    #[serde(rename = "DocProjectContributor")]
    DocProjectContributor,
    #[cfg_attr(feature = "cli", value(name = "DocProjectViewer"))]
    #[serde(rename = "DocProjectViewer")]
    DocProjectViewer,
    #[cfg_attr(feature = "cli", value(name = "OrganizationAdmin"))]
    #[serde(rename = "OrganizationAdmin")]
    OrganizationAdmin,
    #[cfg_attr(feature = "cli", value(name = "OrganizationManager"))]
    #[serde(rename = "OrganizationManager")]
    OrganizationManager,
    #[cfg_attr(feature = "cli", value(name = "OrganizationMember"))]
    #[serde(rename = "OrganizationMember")]
    OrganizationMember,
}
impl std::fmt::Display for RoleDefinitionIdEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            RoleDefinitionIdEnum::ApiProjectAdmin => "ApiProjectAdmin",
            RoleDefinitionIdEnum::ApiProjectContributor => "ApiProjectContributor",
            RoleDefinitionIdEnum::ApiProjectViewer => "ApiProjectViewer",
            RoleDefinitionIdEnum::DocProjectAdmin => "DocProjectAdmin",
            RoleDefinitionIdEnum::DocProjectContributor => "DocProjectContributor",
            RoleDefinitionIdEnum::DocProjectViewer => "DocProjectViewer",
            RoleDefinitionIdEnum::OrganizationAdmin => "OrganizationAdmin",
            RoleDefinitionIdEnum::OrganizationManager => "OrganizationManager",
            RoleDefinitionIdEnum::OrganizationMember => "OrganizationMember",
        };
        write!(f, "{}", str_val)
    }
}
