/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct StatelessGenerateSdk {
    #[cfg_attr(feature = "cli", arg(id = "base-url", long = "base-url"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub base_url: Option<String>,
    #[cfg_attr(feature = "cli", arg(id = "language", long = "language"))]
    pub language: crate::models::GenerationLanguageEnum,
    #[cfg_attr(feature = "cli", arg(id = "openapi", long = "openapi"))]
    #[cfg_attr(
        feature = "cli",
        arg(value_parser = crate::core::clap::parse_upload_file)
    )]
    pub openapi: crate::UploadFile,
    #[cfg_attr(feature = "cli", arg(id = "package-name", long = "package-name"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub package_name: Option<String>,
}
