/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Clone)]
#[serde(untagged)]
pub enum Union {
    LatestApiLinkPolicy(crate::models::LatestApiLinkPolicy),
    PinnedApiLinkPolicy(crate::models::PinnedApiLinkPolicy),
}
impl Default for Union {
    fn default() -> Self {
        Union::PinnedApiLinkPolicy(Default::default())
    }
}
