/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct UpdateApiLinkGroup {
    #[cfg_attr(feature = "cli", arg(id = "nav-label", long = "nav-label"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nav_label: Option<String>,
    #[cfg_attr(feature = "cli", arg(id = "slug", long = "slug"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}
