/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct UpdateApiLink {
    #[cfg_attr(feature = "cli", arg(id = "api-version", long = "api-version"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    #[cfg_attr(
        feature = "cli",
        arg(id = "build-request-enabled", long = "build-request-enabled")
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub build_request_enabled: Option<bool>,
    #[cfg_attr(
        feature = "cli",
        arg(id = "include-mock-server", long = "include-mock-server")
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub include_mock_server: Option<bool>,
    #[cfg_attr(feature = "cli", arg(id = "nav-label", long = "nav-label"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub nav_label: Option<String>,
    #[cfg_attr(feature = "cli", arg(id = "policy", long = "policy"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub policy: Option<crate::models::ApiLinkPolicyEnum>,
    #[cfg_attr(feature = "cli", arg(id = "slug", long = "slug"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}
