/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct UpdateDocProject {
    #[cfg_attr(feature = "cli", arg(id = "logos", long = "logos"))]
    #[cfg_attr(
        feature = "cli",
        arg(
            value_parser = crate::core::clap::parse_json::<crate::models::UpdateDocProjectLogos>
        )
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub logos: Option<crate::models::UpdateDocProjectLogos>,
    #[cfg_attr(feature = "cli", arg(id = "settings", long = "settings"))]
    #[cfg_attr(
        feature = "cli",
        arg(
            value_parser = crate::core::clap::parse_json::<crate::models::UpdateDocProjectSettings>
        )
    )]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub settings: Option<crate::models::UpdateDocProjectSettings>,
    #[cfg_attr(feature = "cli", arg(id = "title", long = "title"))]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}
