/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct User {
    #[cfg_attr(feature = "cli", arg(id = "avatar-url", long = "avatar-url"))]
    pub avatar_url: String,
    #[cfg_attr(feature = "cli", arg(id = "email", long = "email"))]
    pub email: String,
    #[cfg_attr(feature = "cli", arg(id = "first-name", long = "first-name"))]
    pub first_name: String,
    #[cfg_attr(feature = "cli", arg(id = "id", long = "id"))]
    pub id: String,
    #[cfg_attr(feature = "cli", arg(id = "last-name", long = "last-name"))]
    pub last_name: String,
    #[cfg_attr(
        feature = "cli",
        arg(id = "organization-role", long = "organization-role")
    )]
    pub organization_role: crate::models::OrganizationRoleEnum,
}
