/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct UserApiKey {
    #[cfg_attr(feature = "cli", arg(id = "api-key", long = "api-key"))]
    pub api_key: String,
}
