/// File Generated by Sideko (sideko.dev)
#[cfg_attr(feature = "cli", derive(clap::Args))]
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
pub struct UserProjectRole {
    #[cfg_attr(
        feature = "cli",
        arg(id = "project-id-or-name", long = "project-id-or-name")
    )]
    pub project_id_or_name: String,
    #[cfg_attr(feature = "cli", arg(id = "project-type", long = "project-type"))]
    pub project_type: crate::models::ProjectTypeEnum,
    #[cfg_attr(feature = "cli", arg(id = "role", long = "role"))]
    pub role: crate::models::ProjectRoleEnum,
}
