/// File Generated by Sideko (sideko.dev)
#[derive(serde::Serialize, serde::Deserialize, Debug, Default, Clone)]
#[cfg_attr(feature = "cli", derive(clap::ValueEnum))]
pub enum VersionTypeEnum {
    #[default]
    #[cfg_attr(feature = "cli", value(name = "latest"))]
    #[serde(rename = "latest")]
    Latest,
}
impl std::fmt::Display for VersionTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let str_val = match self {
            VersionTypeEnum::Latest => "latest",
        };
        write!(f, "{}", str_val)
    }
}
