/// File Generated by Sideko (sideko.dev)
mod client;
mod core;
pub mod environment;
pub mod models;
mod request_types;
pub use client::Client;
pub use core::{
    error::{ApiError, Error},
    patch::Patch,
    response::BinaryResponse,
    upload_file::UploadFile,
};
pub use request_types::*;
pub type SdkResult<T> = Result<T, crate::core::error::Error>;
